### ISSUE TITLE
Android Studio Design Editor

### ISSUE THREAD

**Issue by demelvin** [JoanZapata/android-iconify#170] opened 2016-05-06 18:35 UTC
When attempting to preview the Iconify view/widget in the Android Studio layout design editor I only see the style text e.g. {fa-cog}. However, when I launch to the device the icon does render fine. Is there any way to get the design editor to render the icon correctly? 

I searched for a solution to this with no luck. The only thing I found that was remotely close was this issue #45 so I figured I would open a new one and see if anybody has a solution. I apologize in advance if this question has already been asked and resolved. Thanks for creating such a great lib.

**Comment by JoanZapata** [comment] 2016-05-18 06:04
Graphic preview and design editor actually use the same renderer, so it's a duplicate of #45.

**Closed by JoanZapata** 2016-05-18 06:04 UTC
