### ISSUE TITLE
Icon is not vertically centered.

### ISSUE THREAD

**Issue by ladjzero** [JoanZapata/android-iconify#115] opened 2015-09-05 06:29 UTC
Here is my xml snippet

    <com.joanzapata.iconify.widget.IconTextView
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_vertical"
        android:gravity="center"
        android:text="{md-info 24sp}信息"
        android:textColor="@color/dark_primary"
        android:textSize="18sp"/>

    <com.joanzapata.iconify.widget.IconTextView
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_vertical"
        android:gravity="center"
        android:text="{md-info 24sp}info"
        android:textColor="@color/dark_primary"
        android:textSize="18sp"/>

The icon and the text aside are not aligned.
![20150905_142119_screenshot_zte g717c](https://cloud.githubusercontent.com/assets/4110311/9698093/564bfba2-53da-11e5-9c59-7386973ae31a.jpeg)

Is there anything wrong in my xml?

**Comment by JoanZapata** [comment] 2015-09-08 10:07
Nothing wrong, I'll investigate it, thanks for the report.

**Comment by JoanZapata** [comment] 2015-09-12 18:20
It's actually a duplicate of #118 which just got fixed.

**Closed by JoanZapata** 2015-09-12 18:20 UTC
Labels: bug

**Comment by sourab-sharma** [comment] 2016-09-23 12:17
In class:
 `com.joanzapata.iconify.internalCustomTypefaceSpan`

Method: 
`draw(Canvas canvas, CharSequence text,int start, int end, float x, int top, int y,int bottom, Paint paint)`

I made the following change to align "{fa-arrows-h}" in center of two strings.
It was baseaglined by default somehow and was not vertically centered in my case.

```
float centerY =0f;
        if (rotate) {
            float rotation = (System.currentTimeMillis() - rotationStartTime) / (float) ROTATION_DURATION * 360f;
            float centerX = x + TEXT_BOUNDS.width() / 2f;
             centerY = y - TEXT_BOUNDS.height() / 2f + TEXT_BOUNDS.height() * baselineRatio;
            canvas.rotate(rotation, centerX, centerY);
        }
        else
        {
            centerY = y;
        }
        canvas.drawText(icon,
                x - TEXT_BOUNDS.left,
                rotate?  y - TEXT_BOUNDS.bottom + TEXT_BOUNDS.height() * baselineRatio:centerY, paint);
```
