### ISSUE TITLE
Wrong fonts are being displayed for icontextview

### ISSUE THREAD

**Issue by gurpreet4009** [JoanZapata/android-iconify#101] opened 2015-08-12 08:24 UTC
Hi, i migrated my iconify from 1.xxx to 2.0.4 font awesome and followed the entire migration process but when i placed the fonts for example {fa-times} and {fa-check} on icon text view wrong fonts were being displayed ?? the fonts that were being displayed were can be seen in the screenshot.. this was tested on android version 5.0. and also on android version 4.2.2 kitkat the the same fonts were being displayed but the size of the fonts were barely visible ?

![screenshot_2015-08-11-15-43-37_1024](https://cloud.githubusercontent.com/assets/13749079/9219572/1cc010c8-40dc-11e5-8836-99a74bbdbe06.png)

**Comment by JoanZapata** [comment] 2015-08-12 14:06
Duplicate of #100, fixed in 2.0.5, sorry for the inconvenience!

**Closed by JoanZapata** 2015-08-12 14:06 UTC
